### ISSUE TITLE
Support for adjusting interactiveDrawModeUpdateDelayMillis 

### ISSUE THREAD

**Issue by yschimke** [Splitties/ComposeOClock#12]
Ideally for a watchface that is minute level, it would only update on the minute and when state or complications change.

```
renderer.interactiveDrawModeUpdateDelayMillis = 1.seconds.inWholeMilliseconds
```

This probably means disconnecting from the Choreographer frames.

Not sure if possible, but figure I would log. It would be nice to have watchfaces that can be super efficient as demonstrated in benchmarks.

**Comment by LouisCAD** [comment]
The default is already 60 seconds + dynamic updates.

Everything that happens more often than that is because code is reading state that updates more often (e.g. animations, `secondsWithMillis`, some derived state using `secondsWithMillis` or `seconds` and having its derived value change…).

The way `renderer.interactiveDrawModeUpdateDelayMillis` is used inside `androidx.wear.watchface` isn't any more optimized than calling `renderer.invalidate()` with a delayed callback (using `Handler.postDelayed`).

I'm closing this since it's probably not needed, but I asked if using `Choreographer` has any undocumented, costly side-effects that might be worth avoiding, through combined usage of `Handler.postDelayed` + rarer use of `Choreographer`.

I'll update here when I get a response.
